site_name: Jaappko Site

#nav:
#- Home: 'index.md'
#- User Guide:
#    - 'Writing your docs': 'user-guide/another_file.md'
#    - 'Styling your docs1': 'user-guide/another_file.md'
#    - 'Styling your docs2': 'user-guide/another_file.md'
#    - 'Styling your docs3': 'user-guide/another_file.md'
#- About:
#    - 'License': 'about/license.md'
#    - 'Release Notes': 'about/release-notes.md'

theme:
  name: material
  features:
    - navigation.tabs
#    - navigation.sections
#    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/"  target="_blank" rel="noopener">Jaappko</a>